module.exports = {
  validator: {
    $and: [
      {
        $expr: {
          $gte: ["$updatedOn", "$createdOn"],
        },
      },
      {
        $jsonSchema: {
          bsonType: "object",
          required: [
            "_id",
            "createdOn",
            "updatedOn",
            "name",
            "retreatIsoDate",
            "date",
            "price",
            "location",
            "upcomingTitle",
            "upcomingDesc",
            "upcomingImgPath",
            "upcomingUrlPath",
            "exploreShown",
            "active",
          ],
          additionalProperties: false,
          properties: {
            _id: {
              bsonType: "string",
              description: "id of string type generated by uuid package.",
            },
            createdOn: {
              bsonType: "date",
              description:
                "createdOn of iso date type is required. Defaults to booking date.",
            },
            updatedOn: {
              bsonType: "date",
              description:
                "updatedOn of iso date type is required. Must be greater than or equwals to createdOn.",
            },
            name: {
              bsonType: "string",
              description: "retreatName of string datatype is required.",
            },
            retreatIsoDate: {
              bsonType: "date",
              description: "retreatIsoDate of iso date datatype is required.",
            },
            date: {
              bsonType: "string",
              description:
                "date of string datatype is required. This is in the human readable format to be shown in website.",
            },
            price: {
              bsonType: "double",
              description: "price of double datatype without $ is required.",
            },
            location: {
              bsonType: "string",
              description: "location of string datatype is required.",
            },
            promotion: {
              bsonType: "string",
              description: "promotion of string datatype is optional.",
            },
            upcomingTitle: {
              bsonType: "string",
              description: "upcomingTitle of string datatype is required.",
            },
            upcomingDesc: {
              bsonType: "string",
              description: "upcomingDesc of string datatype is required.",
            },
            upcomingImgPath: {
              bsonType: "string",
              description: "upcomingImgPath of string datatype is required.",
            },
            upcomingUrlPath: {
              bsonType: "string",
              description: "upcomingUrlPath of string datatype is required.",
            },
            emailDesc: {
              bsonType: "string",
              description:
                "emailDesc of string datatype is optional. Information about retreat after the words 'This will be'",
            },
            exploreTitle: {
              bsonType: "string",
              description:
                "exploreTitle of string datatype is optional. To be added after retreat is completed.",
            },
            exploreDesc: {
              bsonType: "string",
              description:
                "exploreDesc of string datatype is optional. To be added after retreat is completed.",
            },
            exploreUrlPath: {
              bsonType: "string",
              description:
                "exploreUrlPath of string datatype is optional. To be added after retreat is completed.",
            },
            exploreImgPath: {
              bsonType: "string",
              description:
                "exploreImgPath of string datatype is optional. To be added after retreat is completed.",
            },
            exploreShown: {
              bsonType: "bool",
              description:
                "exploreShown of boolean datatype is required. Indicates whether retreat is shown on explore page.",
            },
            active: {
              bsonType: "bool",
              description:
                "active of boolean datatype is required. Indicates whether it allows booking & shown on upcoming page.",
            },
          },
        },
      },
    ],
  },
};
