module.exports = {
  validator: {
    $and: [
      {
        $expr: {
          $gte: ["$updatedOn", "$createdOn"],
        },
      },
      {
        $jsonSchema: {
          bsonType: "object",
          required: [
            "_id",
            "createdOn",
            "updatedOn",
            "name",
            "retreatIsoDate",
            "date",
            "price",
            "location",
            "title",
            "caption",
            "emailDesc",
            "active",
          ],
          additionalProperties: false,
          properties: {
            _id: {
              bsonType: "string",
              description: "id of string type generated by uuid package.",
            },
            createdOn: {
              bsonType: "date",
              description:
                "createdOn of iso date type is required. Defaults to booking date.",
            },
            updatedOn: {
              bsonType: "date",
              description:
                "updatedOn of iso date type is required. Must be greater than or equals to createdOn.",
            },
            name: {
              bsonType: "string",
              description: "retreatName of string datatype is required.",
            },
            retreatIsoDate: {
              bsonType: "date",
              description: "retreatIsoDate of iso date datatype is required.",
            },
            date: {
              bsonType: "string",
              description:
                "date of string datatype is required. This is in the human readable format to be shown in website.",
            },
            price: {
              bsonType: "double",
              description: "price of double datatype without $ is required.",
            },
            location: {
              bsonType: "string",
              description: "location of string datatype is required.",
            },
            promotion: {
              bsonType: "string",
              description: "promotion of string datatype is optional.",
            },
            title: {
              bsonType: "string",
              description: "title of string datatype is required.",
            },
            caption: {
              bsonType: "string",
              description: "caption of string datatype is required.",
            },
            emailDesc: {
              bsonType: "string",
              description: "emailDesc of string datatype is required.",
            },
            emailOtherInfo: {
              bsonType: "string",
              description: "emailOtherInfo of string datatype is optional.",
            },
            active: {
              bsonType: "bool",
              description: "active of boolean datatype is required.",
            },
          },
        },
      },
    ],
  },
};
